LinuxFile reused scratch buffers ensuring size was usable.  But the …
Pi4J/pi4j pull request #331
Opened 2024-03-01 02:03 UTC by taartspi

…limit value cannot be modified so later usage failed as an intended overwrite

Modified both methods that return a buffer.   The methods ensured the an existing buffer was large enough for the new request and returned it. But its new usage may containa greater limit value.   I could not alter the limit value of an existing buffer, instead if an old buffer exists I remove it an allocate a new buffer.

This is an answer to a  post.  If you agree with this, can you spin a 2.5.1 snap shot so this user can progress.

@eitch @FDelporte

2024-03-01 07:25 UTC, eitch requested changes
@taartspi 

You test if the buffer is not null, and then remove it, creating a new buffer. Further you set the byte ordering, but since it's a new byte buffer, i think that is not necessary.

I think we could reduce the code to this:

```
final int byteSize = size * 4;
if (byteSize > localBufferSize)
    throw new ScratchBufferOverrun();
IntBuffer buf = ByteBuffer.allocateDirect(localBufferSize).asIntBuffer();
localOffsetsBuffer.set(buf);
return buf;
```

Do you agree?

2024-03-01 07:29 UTC, eitch commented
Further if i look at the old code, then we reuse the buffer... Are we sure this is ok, to just always write a new buffer? Are we not using the buffers in multiple calls in some way?

2024-03-01 13:55 UTC, taartspi commented
My last sentence in the pr about further validation for reuse.  We could test if the limit is the same or now less and i think reuse is ok. I would need to decide if there are other attributes that require similar validation.       And your code suggestion. I must retest but i think this will not handle the new limit being greater.   Will be late my daytime before i can do this work

2024-03-03 00:22 UTC, taartspi commented on libraries/pi4j-library-linuxfs/src/main/java/com/pi4j/library/linuxfs/LinuxFile.java
Robert.  U asked about reducing this code. The nativeOrder does alter the buffer and should remain.   I did not challenge the comment that nativeOrder be set prior to making the buffer an IntBuff
```suggestion

```

2024-03-03 00:42 UTC, taartspi commented
-Git repeated saying that the push failed for my local being behind.  Seems it did accomplish something each attempt until I figured out how to fix this without using some dangerous force.  That left these extra commits, sorry about that.

2024-03-03 07:15 UTC, eitch reviewed
Ok, since you tested, then i am sure it is ok

2024-03-03 07:15 UTC, eitch approved these changes

2024-03-03 07:15 UTC, merged