linuxfs-pwm provider fixes for Pi5 operation. Default now pwmchip2, w…
Pi4J/pi4j pull request #339
Opened 2024-04-01 16:41 UTC by taartspi

…as chip 0. After initial export of a channel, sleep quarter second so SSD card compllets directory and individual device file creation. Bug fix when user calls getActualFreq prior to setting PWM channel ON.

2024-04-04 13:50 UTC, taartspi commented on plugins/pi4j-plugin-linuxfs/src/main/java/com/pi4j/plugin/linuxfs/internal/LinuxPwm.java
> +    public static int DEFAULT_PWM_CHIP = 2;
test comment

2024-04-04 14:18 UTC, eitch requested changes

2024-04-04 14:18 UTC, eitch commented on plugins/pi4j-plugin-linuxfs/src/main/java/com/pi4j/plugin/linuxfs/provider/pwm/LinuxFsPwm.java
> +                Thread.sleep(250);
Is this really needed? Maybe the export method need to do this check? What fails without this sleep?

2024-04-04 14:18 UTC, eitch commented on plugins/pi4j-plugin-linuxfs/src/main/java/com/pi4j/plugin/linuxfs/internal/LinuxPwm.java
> +    public static int DEFAULT_PWM_CHIP = 2;
Doesn't this mean, that it won't work on the Pi4 anymore? Shouldn't we be doing a check for the environment?

2024-04-04 21:34 UTC, taartspi commented on plugins/pi4j-plugin-linuxfs/src/main/java/com/pi4j/plugin/linuxfs/provider/pwm/LinuxFsPwm.java
> +                Thread.sleep(250);
In the push last night the delay is 70 ms, a bit less pain.   The app does pwm.on()x,y);   If an export was not previously done, the code does an export and immediately call to set the period and calls to set the cycle.  Setting the period fails with an access violation.  In the export method we don't what will occur next and the delay fixes the exception.  My assumption is the SSD has not completed the creation of the pwmX directory and contained  files.   I used this code very little on my Pi4 long ago and it worked. When we have system aware code in use I can verify that the Pi4 does not have a problem with no delay.    Why 70 ms.  25 failed always, 30 worked nearly everytime.  So although 35 might have worked with my fast SSD I doubled that to 70 assuming users with lesser quality SSD will need a greater delay.

2024-04-05 11:50 UTC, eitch commented on plugins/pi4j-plugin-linuxfs/src/main/java/com/pi4j/plugin/linuxfs/provider/pwm/LinuxFsPwm.java
> +                Thread.sleep(250);
The export will create a virtual directory in the kernel's memory space. This should not have anything to do with the attached storage. But it is certainly possible, that it takes the kernel a few milliseconds longer to configure the hardware for this, so i guess we'll keep these 70ms.

2024-04-05 13:54 UTC, taartspi commented on plugins/pi4j-plugin-linuxfs/src/main/java/com/pi4j/plugin/linuxfs/provider/pwm/LinuxFsPwm.java
> +                Thread.sleep(250);
Ok   Stay 70.  I show my need to learn more on this.  Sometime maybe i will do more kernel learning to understand what is syncronous and also how the storage is really used

2024-04-05 13:56 UTC, taartspi commented on plugins/pi4j-plugin-linuxfs/src/main/java/com/pi4j/plugin/linuxfs/internal/LinuxPwm.java
> +    public static int DEFAULT_PWM_CHIP = 2;
So yes. When franks Context update expose the machine type i can set the chip number correctly

2024-04-08 06:49 UTC, eitch approved these changes

2024-04-08 06:49 UTC, merged